<a href="https://colab.research.google.com/github/rdntmsn/Harmony360/blob/main/HAR360_Untitled_Notebook_Promotion_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HAR360 Untitled Notebook Promotion Notebook

Promotes high-value `Untitled*.ipynb` notebooks discovered by the Untitled Notebook Scanner into `HAR360_MASTER/canonical_staging` as evidence-backed recovery assets.

In [ ]:
# ===============================
# CELL 1 — MOUNT GOOGLE DRIVE
# ===============================

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ===============================
# CELL 2 — IMPORTS
# ===============================

from pathlib import Path
from datetime import datetime
import json
import shutil
import hashlib
import pandas as pd

In [ ]:
# ===============================
# CELL 3 — CONFIGURATION
# ===============================

MASTER_ROOT = Path('/content/drive/MyDrive/HAR360_MASTER')
UNTITLED_SCAN_ROOT = MASTER_ROOT / 'untitled_notebook_scan'
UNTITLED_REPORTS_ROOT = UNTITLED_SCAN_ROOT / 'reports'
UNTITLED_CLASSIFIED_ROOT = UNTITLED_SCAN_ROOT / 'classified'

CANONICAL_STAGING_ROOT = MASTER_ROOT / 'canonical_staging'
PROMOTION_ROOT = CANONICAL_STAGING_ROOT / '09_untitled_recovery'
PROMOTION_REPORTS_ROOT = PROMOTION_ROOT / 'reports'

for folder in [PROMOTION_ROOT, PROMOTION_REPORTS_ROOT]:
    folder.mkdir(parents=True, exist_ok=True)

# Minimum score for automatic promotion. Lower if needed.
MIN_PROMOTION_SCORE = 150.0

# Categories worth promoting into canonical staging.
PROMOTE_CATEGORIES = {
    'canonical_reconstruction',
    'core_runtime',
    'registry_tools',
    'trainer_ai',
    'tln_timeline',
    'guardian_codex',
    'economics_finance',
}

print('✅ Configuration ready')
print('Untitled scan root:', UNTITLED_SCAN_ROOT)
print('Promotion root:', PROMOTION_ROOT)

✅ Configuration ready
Untitled scan root: /content/drive/MyDrive/HAR360_MASTER/untitled_notebook_scan
Promotion root: /content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery

In [ ]:
# ===============================
# CELL 4 — HELPERS
# ===============================

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()

def safe_name(name: str) -> str:
    keep = []
    for ch in str(name):
        if ch.isalnum() or ch in ('-', '_', '.', ' '):
            keep.append(ch)
        else:
            keep.append('_')
    return ''.join(keep).strip().replace(' ', '_')

def latest_registry_csv() -> Path | None:
    files = sorted(
        UNTITLED_REPORTS_ROOT.glob('UNTITLED_NOTEBOOK_REGISTRY_*.csv'),
        key=lambda p: p.stat().st_mtime,
        reverse=True
    )
    return files[0] if files else None

def resolve_source_path(row) -> Path | None:
    # Prefer the original path from the registry.
    original = Path(str(row.get('path', '')))
    if original.exists():
        return original

    # Fall back to classified copy if available.
    suggested = str(row.get('suggested_name', ''))
    category = str(row.get('category', ''))
    if suggested and category:
        candidate = UNTITLED_CLASSIFIED_ROOT / category / suggested
        if candidate.exists():
            return candidate

    # Search classified tree for the original name.
    name = str(row.get('name', ''))
    if name:
        matches = list(UNTITLED_CLASSIFIED_ROOT.rglob(name))
        if matches:
            return matches[0]

    return None

print('✅ Helpers loaded')

✅ Helpers loaded

In [ ]:
# ===============================
# CELL 5 — LOAD LATEST UNTITLED REGISTRY
# ===============================

registry_file = latest_registry_csv()

if registry_file is None:
    raise FileNotFoundError(
        f'No UNTITLED_NOTEBOOK_REGISTRY_*.csv found in {UNTITLED_REPORTS_ROOT}. Run the scanner notebook first.'
    )

records_df = pd.read_csv(registry_file)

print('✅ Loaded registry:')
print(registry_file)
print('Records:', len(records_df))

if not records_df.empty:
    display(records_df.head(20))

✅ Loaded registry:
/content/drive/MyDrive/HAR360_MASTER/untitled_notebook_scan/reports/UNTITLED_NOTEBOOK_REGISTRY_20260603_201957.csv
Records: 26

,path,name,parent,size_bytes,sha256,cell_count,code_cell_count,markdown_cell_count,harmony_score,category,suggested_name,classes,functions,imports,decorators,has_harmony360_class,has_h360_sync,has_har360,preview
0,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled5.ipynb,/content/drive/MyDrive/Colab Notebooks,285498,4e1ded8c5750a7d4bc603f6e9da6c629de1fc7a560ccd2...,13,13,0,1610.0,canonical_reconstruction,canonical_reconstruction__crewai_canonical_rec...,NaN,"classify_file, clean_text, count_family, count...","bs4, collections, csv, datetime, docx, google....",NaN,False,False,True,# ============================================...
1,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled8.ipynb,/content/drive/MyDrive/Colab Notebooks,343046,a15b2acb28d5097795b2f6f9b1caa195844653ec905a93...,32,32,0,838.0,registry_tools,registry_tools__DocumentGraph.ipynb,"DocumentGraph, DocumentMediaConverter, Documen...","__init__, build_class_index, build_concept_ind...","__future__, argparse, ast, collections, datacl...",dataclass,False,False,True,# ============================================...
2,/content/drive/MyDrive/Harmony360/Untitled0.ipynb,Untitled0.ipynb,/content/drive/MyDrive/Harmony360,197833,2b8c574c467be91fb12ded6aa598eafc83e43fb864f67e...,19,19,0,529.0,core_runtime,core_runtime__Harmony360.ipynb,"BlackHoleInformation, CircleOfFifthsResonator,...","__init__, auto_summarize, auto_summary, basic_...","PIL, chardet, datetime, docx, functools, googl...","classmethod, lru_cache, staticmethod",True,False,True,# cell 1 — one‑time installs !pip install -q p...
3,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled9.ipynb,/content/drive/MyDrive/Colab Notebooks,88518,da574ab07bcd1ebc6d75435f18e99a0ab88623568eca00...,11,11,0,518.0,canonical_reconstruction,canonical_reconstruction__crewai_canonical_rec...,NaN,"parse_python_file, read_text, scan_project, sc...","ast, datetime, google.colab, json, networkx, o...",NaN,False,False,True,# HAR360 MVP BUILD #1 — Cell 1 FIXED # Mount D...
4,/content/drive/MyDrive/Harmony360/Untitled2.ipynb,Untitled2.ipynb,/content/drive/MyDrive/Harmony360,164369,fad19f1f65f7569c05963ee6a0d5d584548561ba8b9ec9...,20,20,0,502.0,trainer_ai,trainer_ai__Harmony360HybridTrainer.ipynb,"Harmony360HybridTrainer, Harmony360Trainer","__init__, _generate_soul_vector, _load_existin...","crewai, datasets, datetime, google.colab, hash...",NaN,True,False,True,# 📦 Step 1: Install necessary packages !pip in...
5,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled12.ipynb,/content/drive/MyDrive/Colab Notebooks,22810,9e62cb1f582d05eb9150cc0425be354ca8c170dc2611f9...,11,10,1,343.0,core_runtime,core_runtime__Harmony360.ipynb,"Harmony360, HoroscopeReq, ResonateReq","__init__, _har360_envelope, _index_path, _seed...","datetime, fastapi, google.colab, harmony360, h...",app.post,True,False,True,# Harmony360 • Resonant Stack (Colab) — Unifie...
6,/content/drive/MyDrive/Harmony360/Untitled5.ipynb,Untitled5.ipynb,/content/drive/MyDrive/Harmony360,197780,410e3db7161c94fa595b69644c873da1f01800ca5a9f77...,15,15,0,299.0,trainer_ai,trainer_ai__registry_tool.ipynb,NaN,"load_har360_files, tokenize","datasets, datetime, google.colab, json, loguru...",NaN,False,False,True,# ╔══════════════════════════════════════════╗...
7,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled6.ipynb,/content/drive/MyDrive/Colab Notebooks,16474,bae0a7beed298e1de683ef64ec1eca5bb160c7bae7bcca...,6,6,0,252.0,canonical_reconstruction,canonical_reconstruction__crewai_canonical_rec...,NaN,"build_outputs, parse_python_classes, rank_clas...","ast, collections, crewai, datetime, json, netw...",NaN,False,False,True,# ============================================...
8,/content/drive/MyDrive/Harmony360/Untitled9.ipynb,Untitled9.ipynb,/content/drive/MyDrive/Harmony360,105563,9eb4cede89bf14cb89073b17d12e2f69b67bec74714b56...,7,7,0,222.0,core_runtime,core_runtime__Harmony360.ipynb,"Harmony360, QuantumEntropyField","__init__, calculate_entropy_drift, current_tim...","datetime, docx, google.colab, json, numpy, sen...",NaN,True,False,True,from google.colab import drive drive.mount('/c...
9,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled2.ipynb,/content/drive/MyDrive/Colab Notebooks,7820,92f45385afbeb3fed8701855832e2dfd45a9a4da5d41e8...,1,1,0,199.0,tln_timeline,tln_timeline__Harmony360Core.ipynb,"Harmony360Core, ResonanceOutput","align, energy, eta, eta_convergence, fractal, ...","__future__, dataclasses, math","dataclass, staticmethod",True,False,False,"# Harmony360 Core Physics Engine """""" Harmony36..."
10,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled14.ipynb,/content/drive/MyDrive/Colab Notebooks,6135,6bb841856da3728ea2a48e86a833ed7b35b46890bf529a...,1,1,0,197.0,core_runtime,core_runtime__Untitled14.ipynb,NaN,NaN,NaN,NaN,True,False,False,diff --git a//dev/null b/harmony360/core.py in...
11,/content/drive/MyDrive/Harmony360/Untitled3.ipynb,Untitled3.ipynb,/content/drive/MyDrive/Harmony360,6354,12c9a66dc271f426dc5650b6275f8ce2b250d330db816b...,8,8,0,186.0,guardian_codex,guardian_codex__Harmony360.ipynb,"GuardianOverlay, Harmony360","__init__, consciousness_evolution, consciousne...","datetime, hashlib, json, numpy, scipy.constant...",NaN,True,False,False,# harmony360_core.py import numpy as np import...
12,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled0.ipynb,/content/drive/MyDrive/Colab Notebooks,12505,c61ab7f682e7ea963a6f2e7671474339a3335b0cd36ba4...,3,3,0,185.0,economics_finance,economics_finance__Harmony360Core.ipynb,"AGNFeedbackResonator, Har360Ingestor, Harmony3...","__init__, consciousness_index, detect_cycles, ...","datetime, docx, google.colab, hashlib, json, l...",NaN,True,False,True,# ========================================== #...
13,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled11.ipynb,/content/drive/MyDrive/Colab Notebooks,16056,dd9119dbe1d72df671dc1db45eacfa39456294e96966e0...,1,1,0,178.0,tln_timeline,tln_timeline__Harmony360.ipynb,"Harmony360, LHTConfig, LHTSession, LightHealin...","__init__, anchor_to_tln, binaural_pair, estima...","__future__, dataclasses, datetime, harmony360,...",dataclass,True,False,True,# light_healing_technology.py # Harmony360 sub...
14,/content/drive/MyDrive/Harmony360/Untitled10.i...,Untitled10.ipynb,/content/drive/MyDrive/Harmony360,6240,d2ef0cddc7d793713a6061ea36cb6909461588bf82ce6d...,1,1,0,165.0,core_runtime,core_runtime__h360_sync_runtime.ipynb,NaN,"decorator, h360_sync, wrapper","datetime, functools, json, loguru, math, numpy...",wraps,False,True,True,# === HARMONY360 V11: SETUP & SYNCHRONIZER (La...
15,/content/drive/MyDrive/Untitled0.ipynb,Untitled0.ipynb,/content/drive/MyDrive,182335,228171ff30f1ca65c64ffb2cac7f50c689b50728503890...,11,7,4,121.0,trainer_ai,trainer_ai__Untitled0.ipynb,NaN,"E_H360, G_H360, P, R_369, R_n, calculate_cri, ...","flask, matplotlib.pyplot, numpy, scipy.constan...",app.route,False,False,False,# **1. CRI Dashboard & EEG Processing (Python)...
16,/content/drive/MyDrive/Harmony360/Untitled7.ipynb,Untitled7.ipynb,/content/drive/MyDrive/Harmony360,5749,e0b4b83ad6232e5f90a954610847660fd602ea4bf97616...,3,3,0,91.0,guardian_codex,guardian_codex__Harmony360Har360.ipynb,Harmony360Har360,"__init__, add_node, create_new, export_report,...","google.colab, json, typing",NaN,True,False,True,from google.colab import drive drive.mount('/c...
17,/content/drive/MyDrive/Harmony360/Untitled8.ipynb,Untitled8.ipynb,/content/drive/MyDrive/Harmony360,2873,686b87fd531de21c7150eaad1d4a9b517ff70d145438f4...,2,2,0,78.0,trainer_ai,trainer_ai__Harmony360Trainer.ipynb,Harmony360Trainer,"__init__, ingest_document, save_training_snaps...","datetime, google.colab, json, loguru, os",NaN,True,False,True,# ========================================== #...
18,/content/drive/MyDrive/Colab Notebooks/Untitle...,Untitled7.ipynb,/content/drive/MyDrive/Colab Notebooks,1634,5e4cb3c23e3ada8a978f27daaf66117460537e43e67579...,1,1,0,56.0,canonical_reconstruction,canonical_reconstruction__registry_tool.ipynb,NaN,NaN,"collections, datetime, networkx, os, pandas, p...",NaN,False,False,True,# ============================================...
19,/content/drive/MyDrive/Harmony360/Untitled1.ipynb,Untitled1.ipynb,/content/drive/MyDrive/Harmony360,8275,213b69746b232fe223da38a26c2cc8138603b21b483bf9...,2,2,0,50.0,core_runtime,core_runtime__Untitled1.ipynb,NaN,"batch_convert_to_har360, clean_filename, conve...","docx, os, pathlib",NaN,False,False,True,"!pip install docx import os, json from pathlib..."

In [ ]:
# ===============================
# CELL 6 — SELECT PROMOTION CANDIDATES
# ===============================

if records_df.empty:
    selected_df = records_df.copy()
else:
    selected_df = records_df[
        (records_df['harmony_score'].astype(float) >= MIN_PROMOTION_SCORE)
        & (records_df['category'].isin(PROMOTE_CATEGORIES))
    ].copy()

selected_df = selected_df.sort_values('harmony_score', ascending=False)

print('Promotion candidates:', len(selected_df))

if not selected_df.empty:
    display(selected_df[['name', 'category', 'harmony_score', 'suggested_name', 'path']].head(50))

Promotion candidates: 15

,name,category,harmony_score,suggested_name,path
0,Untitled5.ipynb,canonical_reconstruction,1610.0,canonical_reconstruction__crewai_canonical_rec...,/content/drive/MyDrive/Colab Notebooks/Untitle...
1,Untitled8.ipynb,registry_tools,838.0,registry_tools__DocumentGraph.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...
2,Untitled0.ipynb,core_runtime,529.0,core_runtime__Harmony360.ipynb,/content/drive/MyDrive/Harmony360/Untitled0.ipynb
3,Untitled9.ipynb,canonical_reconstruction,518.0,canonical_reconstruction__crewai_canonical_rec...,/content/drive/MyDrive/Colab Notebooks/Untitle...
4,Untitled2.ipynb,trainer_ai,502.0,trainer_ai__Harmony360HybridTrainer.ipynb,/content/drive/MyDrive/Harmony360/Untitled2.ipynb
5,Untitled12.ipynb,core_runtime,343.0,core_runtime__Harmony360.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...
6,Untitled5.ipynb,trainer_ai,299.0,trainer_ai__registry_tool.ipynb,/content/drive/MyDrive/Harmony360/Untitled5.ipynb
7,Untitled6.ipynb,canonical_reconstruction,252.0,canonical_reconstruction__crewai_canonical_rec...,/content/drive/MyDrive/Colab Notebooks/Untitle...
8,Untitled9.ipynb,core_runtime,222.0,core_runtime__Harmony360.ipynb,/content/drive/MyDrive/Harmony360/Untitled9.ipynb
9,Untitled2.ipynb,tln_timeline,199.0,tln_timeline__Harmony360Core.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...
10,Untitled14.ipynb,core_runtime,197.0,core_runtime__Untitled14.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...
11,Untitled3.ipynb,guardian_codex,186.0,guardian_codex__Harmony360.ipynb,/content/drive/MyDrive/Harmony360/Untitled3.ipynb
12,Untitled0.ipynb,economics_finance,185.0,economics_finance__Harmony360Core.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...
13,Untitled11.ipynb,tln_timeline,178.0,tln_timeline__Harmony360.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...
14,Untitled10.ipynb,core_runtime,165.0,core_runtime__h360_sync_runtime.ipynb,/content/drive/MyDrive/Harmony360/Untitled10.i...

In [ ]:
# ===============================
# CELL 7 — PROMOTE NOTEBOOKS
# ===============================

promotion_records = []
errors = []
seen_hashes = {}

for _, row in selected_df.iterrows():
    try:
        src = resolve_source_path(row)

        if src is None or not src.exists():
            errors.append({
                'name': row.get('name', ''),
                'path': row.get('path', ''),
                'error': 'source_not_found'
            })
            continue

        file_hash = sha256_file(src)
        category = safe_name(row.get('category', 'review_needed'))
        suggested = safe_name(row.get('suggested_name', src.name))

        dest_dir = PROMOTION_ROOT / category
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest = dest_dir / suggested

        # Avoid overwriting and keep duplicates visible.
        if file_hash in seen_hashes:
            duplicate_of = seen_hashes[file_hash]
            action = 'duplicate_skipped'
        else:
            duplicate_of = ''
            if dest.exists():
                stem = dest.stem
                suffix = dest.suffix
                dest = dest_dir / f'{stem}__promoted_{len(promotion_records)+1}{suffix}'
            shutil.copy2(src, dest)
            seen_hashes[file_hash] = str(dest)
            action = 'copied'

        promotion_records.append({
            'original_name': row.get('name', ''),
            'original_path': str(src),
            'promoted_path': str(dest) if action == 'copied' else '',
            'category': category,
            'harmony_score': float(row.get('harmony_score', 0)),
            'suggested_name': suggested,
            'sha256': file_hash,
            'action': action,
            'duplicate_of': duplicate_of,
        })

    except Exception as e:
        errors.append({
            'name': row.get('name', ''),
            'path': row.get('path', ''),
            'error': repr(e)
        })

promotion_df = pd.DataFrame(promotion_records)
errors_df = pd.DataFrame(errors)

print('Promotion records:', len(promotion_df))
print('Errors:', len(errors_df))

if not promotion_df.empty:
    display(promotion_df.head(50))
if not errors_df.empty:
    display(errors_df)

Promotion records: 15
Errors: 0

,original_name,original_path,promoted_path,category,harmony_score,suggested_name,sha256,action,duplicate_of
0,Untitled5.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,canonical_reconstruction,1610.0,canonical_reconstruction__crewai_canonical_rec...,4e1ded8c5750a7d4bc603f6e9da6c629de1fc7a560ccd2...,copied,
1,Untitled8.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,registry_tools,838.0,registry_tools__DocumentGraph.ipynb,a15b2acb28d5097795b2f6f9b1caa195844653ec905a93...,copied,
2,Untitled0.ipynb,/content/drive/MyDrive/Harmony360/Untitled0.ipynb,/content/drive/MyDrive/HAR360_MASTER/canonical...,core_runtime,529.0,core_runtime__Harmony360.ipynb,2b8c574c467be91fb12ded6aa598eafc83e43fb864f67e...,copied,
3,Untitled9.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,canonical_reconstruction,518.0,canonical_reconstruction__crewai_canonical_rec...,da574ab07bcd1ebc6d75435f18e99a0ab88623568eca00...,copied,
4,Untitled2.ipynb,/content/drive/MyDrive/Harmony360/Untitled2.ipynb,/content/drive/MyDrive/HAR360_MASTER/canonical...,trainer_ai,502.0,trainer_ai__Harmony360HybridTrainer.ipynb,fad19f1f65f7569c05963ee6a0d5d584548561ba8b9ec9...,copied,
5,Untitled12.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,core_runtime,343.0,core_runtime__Harmony360.ipynb,9e62cb1f582d05eb9150cc0425be354ca8c170dc2611f9...,copied,
6,Untitled5.ipynb,/content/drive/MyDrive/Harmony360/Untitled5.ipynb,/content/drive/MyDrive/HAR360_MASTER/canonical...,trainer_ai,299.0,trainer_ai__registry_tool.ipynb,410e3db7161c94fa595b69644c873da1f01800ca5a9f77...,copied,
7,Untitled6.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,canonical_reconstruction,252.0,canonical_reconstruction__crewai_canonical_rec...,bae0a7beed298e1de683ef64ec1eca5bb160c7bae7bcca...,copied,
8,Untitled9.ipynb,/content/drive/MyDrive/Harmony360/Untitled9.ipynb,/content/drive/MyDrive/HAR360_MASTER/canonical...,core_runtime,222.0,core_runtime__Harmony360.ipynb,9eb4cede89bf14cb89073b17d12e2f69b67bec74714b56...,copied,
9,Untitled2.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,tln_timeline,199.0,tln_timeline__Harmony360Core.ipynb,92f45385afbeb3fed8701855832e2dfd45a9a4da5d41e8...,copied,
10,Untitled14.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,core_runtime,197.0,core_runtime__Untitled14.ipynb,6bb841856da3728ea2a48e86a833ed7b35b46890bf529a...,copied,
11,Untitled3.ipynb,/content/drive/MyDrive/Harmony360/Untitled3.ipynb,/content/drive/MyDrive/HAR360_MASTER/canonical...,guardian_codex,186.0,guardian_codex__Harmony360.ipynb,12c9a66dc271f426dc5650b6275f8ce2b250d330db816b...,copied,
12,Untitled0.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,economics_finance,185.0,economics_finance__Harmony360Core.ipynb,c61ab7f682e7ea963a6f2e7671474339a3335b0cd36ba4...,copied,
13,Untitled11.ipynb,/content/drive/MyDrive/Colab Notebooks/Untitle...,/content/drive/MyDrive/HAR360_MASTER/canonical...,tln_timeline,178.0,tln_timeline__Harmony360.ipynb,dd9119dbe1d72df671dc1db45eacfa39456294e96966e0...,copied,
14,Untitled10.ipynb,/content/drive/MyDrive/Harmony360/Untitled10.i...,/content/drive/MyDrive/HAR360_MASTER/canonical...,core_runtime,165.0,core_runtime__h360_sync_runtime.ipynb,d2ef0cddc7d793713a6061ea36cb6909461588bf82ce6d...,copied,

In [ ]:

# ===============================
# CELL 8 — EXPORT PROMOTION REPORTS
# ===============================

from datetime import datetime
import json

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

PROMOTION_ROOT.mkdir(parents=True, exist_ok=True)
PROMOTION_REPORTS_ROOT.mkdir(parents=True, exist_ok=True)

promotion_csv = PROMOTION_REPORTS_ROOT / f"UNTITLED_PROMOTION_REGISTRY_{timestamp}.csv"
promotion_json = PROMOTION_REPORTS_ROOT / f"UNTITLED_PROMOTION_REGISTRY_{timestamp}.json"
errors_csv = PROMOTION_REPORTS_ROOT / f"UNTITLED_PROMOTION_ERRORS_{timestamp}.csv"
report_md = PROMOTION_REPORTS_ROOT / f"UNTITLED_PROMOTION_REPORT_{timestamp}.md"
har360_report = PROMOTION_REPORTS_ROOT / f"untitled_promotion_{timestamp}.har360.json"

promotion_df.to_csv(promotion_csv, index=False)
promotion_df.to_json(promotion_json, orient="records", indent=2)
errors_df.to_csv(errors_csv, index=False)

category_counts = (
    promotion_df["category"].value_counts().to_dict()
    if not promotion_df.empty and "category" in promotion_df.columns
    else {}
)

action_counts = (
    promotion_df["action"].value_counts().to_dict()
    if not promotion_df.empty and "action" in promotion_df.columns
    else {}
)

lines = []
lines.append("# HAR360 Untitled Notebook Promotion Report")
lines.append("")
lines.append(f"- Created: {timestamp}")
lines.append(f"- Source registry: {registry_file}")
lines.append(f"- Selected candidates: {len(selected_df)}")
lines.append(f"- Promotion records: {len(promotion_df)}")
lines.append(f"- Errors: {len(errors_df)}")
lines.append("")
lines.append("## Category Overview")

for cat, count in category_counts.items():
    lines.append(f"- {cat}: {count}")

lines.append("")
lines.append("## Action Overview")

for action, count in action_counts.items():
    lines.append(f"- {action}: {count}")

lines.append("")
lines.append("## Top Promoted Untitled Notebooks")

if not promotion_df.empty:
    sorted_df = promotion_df.sort_values(
        "harmony_score",
        ascending=False
    )

    for _, row in sorted_df.head(30).iterrows():
        lines.append(
            f"- `{row.get('original_name', '')}` "
            f":: score={float(row.get('harmony_score', 0)):.1f} "
            f":: {row.get('category', '')} "
            f":: action={row.get('action', '')} "
            f":: `{row.get('promoted_path', '')}`"
        )

lines.append("")
lines.append("## Next Action")
lines.append(
    "Inspect promoted notebooks and include the highest-value ones "
    "in Harmony360 class/runtime merger evidence."
)

report_md.write_text(
    "\n".join(lines),
    encoding="utf-8"
)

snapshot = {
    "snapshot_type": "HAR360_UNTITLED_NOTEBOOK_PROMOTION",
    "created_at": timestamp,
    "source_registry": str(registry_file),
    "promotion_root": str(PROMOTION_ROOT),
    "reports_root": str(PROMOTION_REPORTS_ROOT),
    "selected_count": int(len(selected_df)),
    "promotion_record_count": int(len(promotion_df)),
    "error_count": int(len(errors_df)),
    "category_counts": category_counts,
    "action_counts": action_counts,
    "records": (
        promotion_df.to_dict(orient="records")
        if not promotion_df.empty
        else []
    ),
}

har360_report.write_text(
    json.dumps(snapshot, indent=2, ensure_ascii=False),
    encoding="utf-8"
)

print("✅ Untitled notebook promotion exported")
print("Promotion CSV:", promotion_csv)
print("Promotion JSON:", promotion_json)
print("Errors CSV:", errors_csv)
print("Report MD:", report_md)
print("HAR360 Report:", har360_report)

✅ Untitled notebook promotion exported
Promotion CSV: /content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery/reports/UNTITLED_PROMOTION_REGISTRY_20260604_000114.csv
Promotion JSON: /content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery/reports/UNTITLED_PROMOTION_REGISTRY_20260604_000114.json
Errors CSV: /content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery/reports/UNTITLED_PROMOTION_ERRORS_20260604_000114.csv
Report MD: /content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery/reports/UNTITLED_PROMOTION_REPORT_20260604_000114.md
HAR360 Report: /content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery/reports/untitled_promotion_20260604_000114.har360.json

In [ ]:
# ===============================
# CELL 9 — FINAL SUMMARY
# ===============================

print()
print('===============================')
print('HAR360 UNTITLED PROMOTION COMPLETE')
print('===============================')
print(f'Selected candidates : {len(selected_df)}')
print(f'Promotion records   : {len(promotion_df)}')
print(f'Errors              : {len(errors_df)}')

print()
print('Promotion folder:')
print(PROMOTION_ROOT)

print()
print('Reports folder:')
print(PROMOTION_REPORTS_ROOT)

print()
print('Top promoted:')
if not promotion_df.empty:
    for _, row in promotion_df.sort_values('harmony_score', ascending=False).head(15).iterrows():
        print(
            f"- {row.get('original_name', '')} "
            f":: score={float(row.get('harmony_score', 0)):.1f} "
            f":: {row.get('category', '')} "
            f":: {row.get('action', '')}"
        )
else:
    print('No notebooks promoted.')

===============================
HAR360 UNTITLED PROMOTION COMPLETE
===============================
Selected candidates : 15
Promotion records   : 15
Errors              : 0

Promotion folder:
/content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery

Reports folder:
/content/drive/MyDrive/HAR360_MASTER/canonical_staging/09_untitled_recovery/reports

Top promoted:
- Untitled5.ipynb :: score=1610.0 :: canonical_reconstruction :: copied
- Untitled8.ipynb :: score=838.0 :: registry_tools :: copied
- Untitled0.ipynb :: score=529.0 :: core_runtime :: copied
- Untitled9.ipynb :: score=518.0 :: canonical_reconstruction :: copied
- Untitled2.ipynb :: score=502.0 :: trainer_ai :: copied
- Untitled12.ipynb :: score=343.0 :: core_runtime :: copied
- Untitled5.ipynb :: score=299.0 :: trainer_ai :: copied
- Untitled6.ipynb :: score=252.0 :: canonical_reconstruction :: copied
- Untitled9.ipynb :: score=222.0 :: core_runtime :: copied
- Untitled2.ipynb :: score=199.0 :: tln_timeline :: copied
- Untitled14.ipynb :: score=197.0 :: core_runtime :: copied
- Untitled3.ipynb :: score=186.0 :: guardian_codex :: copied
- Untitled0.ipynb :: score=185.0 :: economics_finance :: copied
- Untitled11.ipynb :: score=178.0 :: tln_timeline :: copied
- Untitled10.ipynb :: score=165.0 :: core_runtime :: copied